spring:
  application:
    name: payment-service
  config:
    import:
      - classpath:observability.yml
      - classpath:persistence.yml
      - classpath:springdoc.yml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment_service
    username: ${DB_USER:product_user}
    password: ${DB_PASSWORD:product_password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8085
  servlet:
    context-path: /payment

env.base.url.internal.auth: ${INTERNAL_AUTH_SERVER_BASE_URL:http://localhost:8080}

logging.level.dev.agasen.core.payment: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/payment_service
spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
