apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: shopbuddy
build:
  local:
    push: false
  artifacts:
    - image: product
      context: src/backend/core/product-service
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./gradlew :src:backend:core:product-service:build -x test"]
            os: [linux, darwin]
          - command: ["cmd", "/C", "gradlew.bat :src:backend:core:product-service:build -x test"]
            os: [windows]
    - image: gateway
      context: src/backend/infra/api-gateway
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./gradlew :src:backend:infra:api-gateway:build -x test"]
            os: [linux, darwin]
          - command: ["cmd", "/C", "gradlew.bat :src:backend:infra:api-gateway:build -x test"]
            os: [windows]
    - image: auth
      context: src/backend/infra/auth-server
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./gradlew :src:backend:infra:auth-server:build -x test"]
            os: [linux, darwin]
          - command: ["cmd", "/C", "gradlew.bat :src:backend:infra:auth-server:build -x test"]
            os: [windows]
    - image: user
      context: src/backend/core/user-service
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./gradlew :src:backend:core:user-service:build -x test"]
            os: [linux, darwin]
          - command: ["cmd", "/C", "gradlew.bat :src:backend:core:user-service:build -x test"]
            os: [windows]
    - image: k8s-admin
      context: src/backend/infra/k8s-admin
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ["sh", "-c", "./gradlew :src:backend:infra:k8s-admin:build -x test"]
            os: [linux, darwin]
          - command: ["cmd", "/C", "gradlew.bat :src:backend:infra:k8s-admin:build -x test"]
            os: [windows]
#    - image: k8s-dashboard
#      context: src/frontend/k8s-dashboard/k8s-dashboard
#      docker:
#        dockerfile: Dockerfile
manifests:
  # todo: use kustomize
  rawYaml:
    - k8s/base/*.yaml
    - k8s/base/backend/api-gateway/*.yaml
    - k8s/base/backend/auth-server/*.yaml
    - k8s/base/backend/product-service/*.yaml
    - k8s/base/backend/user-service/*.yaml
    - k8s/base/backend/k8s-admin/*.yaml
    #    - k8s/base/frontend/storefront/*.yaml
    #    - k8s/base/frontend/k8s-dashboard/*.yaml
    - k8s/base/infra/postgres/*.yaml
    - k8s/base/infra/redis/*.yaml
    - k8s/base/shared/cert/*.yaml
    - k8s/base/shared/secrets/*.yaml
deploy:
  kubectl: { }
