apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: shopbuddy
build:
  local:
    push: false
  artifacts:
    - image: product
      context: src/backend/core/product-service
      docker:
        dockerfile: Dockerfile
    - image: gateway
      context: src/backend/infra/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: auth
      context: src/backend/infra/auth-server
      docker:
        dockerfile: Dockerfile
    - image: user
      context: src/backend/core/user-service
      docker:
        dockerfile: Dockerfile
    - image: k8s-admin
      context: src/backend/infra/k8s-admin
      docker:
        dockerfile: Dockerfile
    - image: cart
      context: src/backend/core/cart-service
      docker:
        dockerfile: Dockerfile
    - image: order
      context: src/backend/core/order-service
      docker:
        dockerfile: Dockerfile
    - image: payment
      context: src/backend/core/payment-service
      docker:
        dockerfile: Dockerfile
#    - image: k8s-dashboard
#      context: src/frontend/k8s-dashboard/k8s-dashboard
#      docker:
#        dockerfile: Dockerfile
manifests:
  # todo: use kustomize
  rawYaml:
    - k8s/base/*.yaml
    - k8s/base/backend/api-gateway/*.yaml
    - k8s/base/backend/auth-server/*.yaml
    - k8s/base/backend/product-service/*.yaml
    - k8s/base/backend/user-service/*.yaml
    - k8s/base/backend/k8s-admin/*.yaml
    - k8s/base/backend/cart-service/*.yaml
    - k8s/base/backend/order-service/*.yaml
    - k8s/base/backend/payment-service/*.yaml
    #    - k8s/base/frontend/storefront/*.yaml
    #    - k8s/base/frontend/k8s-dashboard/*.yaml
    - k8s/base/infra/postgres/*.yaml
    - k8s/base/infra/redis/*.yaml
    - k8s/base/infra/kafka/*.yaml
    - k8s/base/shared/cert/*.yaml
    - k8s/base/shared/secrets/*.yaml
deploy:
  kubectl: { }
