spring:
  application:
    name: cart-service
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
  config:
    import:
      - classpath:observability.yml
      - classpath:springdoc.yml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${EXTERNAL_AUTH_SERVER_BASE_URL:http://localhost:8080}

server:
  port: 8082
  servlet:
    context-path: /cart

env.base.url:
  internal:
    auth: ${INTERNAL_AUTH_SERVER_BASE_URL:http://localhost:8080}
    cart: ${INTERNAL_CART_SERVICE_BASE_URL:http://localhost:8082}
  external:
    auth: ${EXTERNAL_AUTH_SERVER_BASE_URL:http://localhost:8080}
    cart: ${EXTERNAL_CART_SERVICE_BASE_URL:http://localhost:8082}

logging:
  level:
    dev.agasen.core.cart: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring.config.activate.on-profile: docker
server.port: 8080

spring.data.redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
